//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstOne
{
    
    internal partial class Resource1
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource1.manager == null))
                {
                    Resource1.manager = new System.Resources.ResourceManager("FirstOne.Resource1", typeof(Resource1).Assembly);
                }
                return Resource1.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resource1.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(ResourceManager.GetObject(((short)(id)))));
        }
        internal static System.Drawing.Font GetFont(Resource1.FontResources id)
        {
            return ((System.Drawing.Font)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            droid_reg10 = -27850,
            droid_reg12 = -27848,
            droid_reg11 = -27847,
            droid_reg14 = -27846,
            droid_reg18 = -27842,
            droid_reg24 = -13442,
            droid_reg09 = -7428,
            droid_reg08 = -7427,
            droid_reg32 = 14655,
            droid_reg48 = 24547,
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            pump2 = 2496,
        }
    }
}
